* Hack and Tell, Hyderabad

This is a repository for discussions and wrap-ups of Hack-and-Tell group,
Hyderabad.

We're inspired by the [[http://www.meetup.com/hack-and-tell/][original Hack and Tell in NYC]], like [[hackandtell.org][many others]].

** Hack and Tell

A "show and tell" meet-up for Hackers in Hyderabad

If you've ever visited Hacker News, you've almost certainly seen the "Show HN"
or "Ask HN" posts. Well, it's time to get off the Internet and tell us about it
face to face. We'll provide you with our honest feedback, you provide us with a
great hack, or idea.

** Meetup format

- Members sign up in advance, to present.
- Each presenter has 5 minutes to show off their hack (a tool, library, etc.,
  that they built)
- 5 minutes for the audience to applaud, cry, laugh, inquiry, snore, chew,
  stand, sit, dance, grow, interact, etc.

We hope that the audience provides lots of great feedback and asks interesting
questions!

** Presentation rules

While all technology is fair game, there are a few rules:

- No deckware/varporware. It doesn't have to be completely finished or
  polished, but it does need to be something you've actually made.
- No startup pitches. Ever.
- No work projects [1]. No presentations that are just promoting commercial
  software.

[1]: Let me clarify the "no job projects" rule. We want to promote the
projects that people do in their spare time, for fun, or utility, and
not the kinds of projects that are only applicable to people who work in
your company, or your direct clients. On the other hand, there may be a
project that you've built primarily at work, that solves a /general/
problem that your company has allowed you to release with a libre
license--this is usually fine.

** Code of Conduct and Social Rules

- We strive to be a community that provides a friendly, safe and welcoming
  environment for all, regardless of any race, ethnicity, culture, national
  origin, colour, immigration status, social and economic class, educational
  level, sex, sexual orientation, gender identity and expression, age, size,
  family status, political belief, religion, and mental and physical ability.

- We are a community of professionals, and we conduct ourselves
  professionally. Be kind to others. Do not insult or put down other
  participants. Harassment and other exclusionary behavior aren't
  acceptable. This includes, but is not limited to:

  - Violent threats or language directed against another person.
  - Discriminatory jokes and language.
  - Posting sexually explicit or violent material.
  - Posting (or threatening to post) other people's personally
    identifying information ("doxing").
  - Personal insults, especially those using racist or sexist terms.
  - Unwelcome sexual attention.
  - Advocating for, or encouraging, any of the above behavior.
  - Repeated harassment of others. In general, if someone asks you to stop,
    then stop.

- Violations of the Code of Conduct will be taken seriously, the following
  actions might be taken:

  - Asking a violator to apologize for their actions
  - Suspending a violator's unmoderated posting privileges to the group
  - Removing a violator from an event
  - Banning a violator from future events
  - Removal from the group

  as deemed fit by the organizers.

*** Social Rules

The Social Rules have been lifted from Hacker School's manual and are intended
to be a means of removing obstacles to learning from each other. These rules
are intended to be lightweight (in contrast to the Code of Conduct), and to
make more explicit certain social norms that are normally implicit. The social
rules are designed to curtail specific behavior that Hacker School has found to
be destructive to a supportive, productive, and fun learning environment.

- *No feigning surprise*. You shouldn't act (or be) surprised when people say
  they don't know something. This applies to both technical things ("What?! I
  can't believe you don't know what the stack is!") and non-technical things
  ("You don't know who RMS is?!"). Feigning surprise has absolutely no social
  or educational benefit: When people feign surprise, it's usually to make them
  feel better about themselves and others feel worse.

- *No well-actually's*. A well-actually happens when someone says something
  that's almost - but not entirely - correct, and you say, "well, actually" and
  then give a minor correction. This is especially annoying when the correction
  has no bearing on the actual conversation. Almost all well-actually's in our
  experience are about grandstanding, not truth-seeking.

- *No back-seat driving*. If you overhear people working through a problem, you
  shouldn't intermittently lob advice across the room. This can lead to the
  "too many cooks" problem, but more important, it can be rude and disruptive
  to half-participate in a conversation. This isn't to say you shouldn't help,
  offer advice, or join conversations. On the contrary, we encourage all those
  things. Rather, it just means that when you want to help out or work with
  others, you should fully engage and not just butt in sporadically.

- *No subtle -isms*. The last social rule bans subtle racism, sexism,
  homophobia, transphobia, and other kinds of bias. Subtle -isms are small
  things that make others feel uncomfortable, things that we all sometimes do
  by mistake. For example, saying "It's so easy my grandmother could do it" is
  a subtle -ism. Like the other three social rules, this one is often
  accidentally broken. Like the other three, it's not a big deal to mess up --
  you just apologize and move on.

You are strongly recommended to read the rules, with the full and original
explanation [[https://www.hackerschool.com/manual#sub-sec-social-rules][here]].

*** Violations

- What if someone violates the Code of Conduct?

  - Document as much as you can: time, place, people involved, and what\\
    happened.

  - Please report the violation immediately in person, or via email to the
    event organizer.

- What if someone violates a Social Rule?

  The social rules are meant to be light-weight. While, violating a code of
  conduct is a big deal, it usually isn't hard to avoid doing so. The social
  rules, in contrast, are much harder to avoid breaking and people often make
  mistakes. When this happens, you should point out to that person, and the
  person apologizes and both of you move on. Accidentally breaking social rules
  is common, expected, and readily forgiven.

  Read [[https://www.hackerschool.com/blog/38-subtle-isms-at-hacker-school][this wonderful blog-post]] for a detailed explanation of the Social Rules,
  especially the last one.

*** References

The Code of Conduct is inspired by some great ones from [[https://www.djangoproject.com/conduct/][Django project]], [[https://github.com/rust-lang/rust/wiki/Note-development-policy][Rust
lang]], and [[https://github.com/dchackandtell/code-of-conduct][DC Hack and Tell]]. The social rules have been lifted from Hacker
School's [[https://www.hackerschool.com/manual#sub-sec-social-rules][manual]].
